module.exports = {
    ENUM: {
        HTTP_CODES: {
            BAD_REQUEST: 400,
            DUPLICATE_VALUE: 409,
            FORBIDDEN: 403,
            INTERNAL_SERVER_ERROR: 500,
            METHOD_NOT_ALLOWED: 405,
            MOVED_PERMANENTLY: 301,
            NOT_ACCEPTABLE: 406,
            NOT_FOUND: 404,
            NO_CONTENT_FOUND: 204,
            OK: 200,
            PERMANENT_REDIRECT: 308,
            UNAUTHORIZED: 401,
            UPGRADE_REQUIRED: 426,
            VALIDATION_ERROR: 422,
        },
        ROLE: {
            USER: 'user',
            ADMIN: 'admin',
        },
        PRODUCT_STATE: {
            IN_STOCK: 'in_stock',
            OUT_OF_STOCK: 'out_of_stock',
        },
        COUNT_MODULES: {
            USER: "user",
            CATEGORY: "category",
            SUB_CATEGORY: "sub_category",
            PRODUCT: "product",
        },
        SIZES: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    },
    MESSAGE: {
        TOKEN_REQUIRED: 'Token required.',
        INVALID_TOKEN: 'Invalid token.',
        UNAUTHORIZED: 'Unauthorized.',
        INTERNAL_SERVER_ERROR: 'Internal server error.',
        DUPLICATE_KEY: 'Duplicate key.',
        TOKEN_ALREADY_USED: 'Token already used.',
        INVALID_ROUTE: "Oops! Looks like you're lost.",
        SUCCESS: 'Success.',
        FAILED: 'Failed.',
        NOT_FOUND: 'Not found.',
        INVALID_PASSWORD: 'Invalid password.',
        INVALID_ROLE: 'Invalid role.',
        EMAIL_NOT_FOUND: 'Email not found.',
        OTP_EXPIRED: 'OTP expired.',
        INVALID_OTP: 'Invalid OTP.',
        ALREADY_EXISTS: 'Already exists.',
        DUPLICATE_ENTRY: 'Duplicate entry.',
        CART_EMPTY: 'Cart is empty.',
        NOT_ACTIVE: 'Not active.',
        ACCOUNT_DISABLED: 'Account disabled.',
        PAYMENT_FAILED: 'Payment failed.',
        PAYMENT_ID_USED: 'Payment id already used.',
        INVALID_IMAGE_TYPE: 'Invalid image type.',
        FILE_UPLOAD_FAILED: 'File upload failed.',
        MAX_FILE_UPLOAD_LIMIT: 'Max file upload limit exceeded.',
        FILE_UPLOAD_SUCCESS: 'File uploaded successfully.',
        INVALID_FILE_TYPE: 'Invalid file type.',
        MULTER_ERROR: 'Multer error.',
        INVALID_FIELD_NAME: 'Invalid directory name.',
        PAYMENT_QTY_MISMATCH: 'ProductIds and quantities length mismatch.',
    },
    COLORS: {
        "000000": "Black",
        "808080": "Gray",
        "2F4F4F": "Dark Slate Gray",
        "708090": "Slate Gray",
        "FFFFFF": "White",
        "FFFDD0": "Cream",
        "000080": "Navy Blue",
        "4169E1": "Royal Blue",
        "87CEEB": "Sky Blue",
        "008080": "Teal",
        "40E0D0": "Turquoise",
        "4682B4": "Steel Blue",
        "6A5ACD": "Slate Blue",
        "6495ED": "Cornflower Blue",
        "008000": "Green",
        "808000": "Olive",
        "00FF00": "Lime Green",
        "006400": "Dark Green",
        "228B22": "Forest Green",
        "556B2F": "Dark Olive Green",
        "FFFF00": "Yellow",
        "FFDB58": "Mustard",
        "FFA500": "Orange",
        "FF8C00": "Dark Orange",
        "FF7F50": "Coral",
        "FF0000": "Red",
        "800000": "Maroon",
        "E9967A": "Dark Salmon",
        "FA8072": "Salmon",
        "F08080": "Light Coral",
        "FF6347": "Tomato",
        "800080": "Purple",
        "4B0082": "Indigo",
        "E6E6FA": "Lavender",
        "FFC0CB": "Pink",
        "BC8F8F": "Rosy Brown",
        "A52A2A": "Brown",
        "A0522D": "Sienna",
        "D2691E": "Chocolate",
        "8B4513": "Saddle Brown",
        "D2B48C": "Tan",
        "F4A460": "Sandy Brown",
        "BDB76B": "Dark Khaki",
        "EEE8AA": "Pale Goldenrod",
        "00FFFF": "Cyan",
        "FF00FF": "Magenta",
        "F5F5DC": "Beige",
        "C3B091": "Khaki",
        "DB7093": "Pale Violet Red",
        "CD853F": "Peru"
    }
};